management:
  security:
    enabled: false
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9876/eureka/

