server:
  port: 8901
  
spring:
  application:
    name: hello-service
  boot:
    admin:
      url: http://localhost:9800

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9876/eureka/

management:
  security:
    enabled: false