server:
  port: 9876
  
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://admin:admin@localhost:9876/eureka

security:
  user:
    name: admin
    password: admin
