server:
  port: 9890
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/magicluo0755/spring-cloud-demo
          search-paths: config-repo
          username: magicluo0755
          password: luo@8438932
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9876/eureka/
       

